### ISSUE TITLE
Support for the other token sources? (request body and query string)

### ISSUE THREAD

**Issue by mk-pmb** [takuya-motoshima/bearer-token-parser#2]
[RFC 6750](https://www.ietf.org/rfc/rfc6750.txt) defines 3 possible sources for the bearer token, we currently only support the one from headers. Do you have any plans to add the other two? (`access_token` in request body and `access_token` in URL query string)

**Comment by takuya-motoshima** [comment]
Thank you for your good suggestion.
Supported tokens for Query and Body parameters in v2.0.0.
